language: python
python:
    - "2.7"
    - "3.6"
install:
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda config --add channels rbetz
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest libnetcdf numpy
    - source activate test-environment
    - pip install -i https://pypi.anaconda.org/rbetz/simple vmd-python
    - cd $HOME && wget https://raw.githubusercontent.com/Eigenstate/dabble/master/test/tleap_minimal.tar.gz
    - tar --directory=/opt -xzf tleap_minimal.tar.gz
    - export AMBERHOME="/opt/amber/"
    - cd $AMBERHOME && make -C AmberTools/src/leap/ t
    - python setup.py install
script:
    - python setup.py test
