language: python
python:
    - "3.6"
install:
    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest numpy
    - conda install ambertools=17 -n test-environment -c http://ambermd.org/downloads/ambertools/conda/
    - conda install vmd-python networkx psfgen parmed -n test-environment -c conda-forge
    - source activate test-environment
    - export AMBERHOME="$HOME/miniconda/envs/test-environment"
    - python setup.py install
script:
    - python setup.py test
