#!/bin/bash

# Use our own python to avoid problems
PYTHON="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/miniconda/bin/python"

# Set up PYTHONPATH so it can find VMD and the dabble module
$PYTHON src/init_dabble.py "$@"
