package:
    name: dabble
    version: "2.3.3"

source:
    git_url: https://github.com/drorlab/dabble.git
    git_tag: master

build:
    number: 1

requirements:
    build:
        - python
    run:
        - numpy
        - parmed
        - vmd-python

about:
    home: dabble-md.readthedocs.org
    license: GPL2
    summary: Membrane protein system builder and parameterizer

