package:
    name: dabble
    version: "2.7.9"

source:
    git_url: https://github.com/Eigenstate/dabble.git
    git_tag: master

build:
    number: 1

requirements:
    build:
        - python
        - vmd-python >=2.0.4
        - networkx >=1.11
        - parmed
        - pydot
    run:
        - python
        - vmd-python >=2.0.4
        - parmed
        - networkx >=1.11
        - psfgen
        - pydot

about:
    home: dabble.robinbetz.com
    license: GPL2
    summary: Membrane protein system builder and parameterizer

