package:
    name: dabble
    version: "1.0.0a1"

source:
    git_url: https://github.com/drorlab/dabble.git
    git_tag: master

build:
    features:
        - builder
        - parameterizer
         - vmd

    script: python setup.py install

requirements:
    run:
        - numpy
        - vmd

