package:
    name: dabble-md
    version: "1.3.5"

source:
    git_url: https://github.com/drorlab/dabble.git
    git_tag: master

build:
    number: 1

requirements:
    run:
        - numpy
        - parmed
        - vmd-python

about:
    home: dabble-md.readthedocs.org
    license: GPL2
    summary: Membrane protein system builder and parameterizer

