package:
    name: dabble
    version: "2.7.1"

source:
    git_url: https://github.com/drorlab/dabble.git
    git_tag: master

build:
    number: 1

requirements:
    build:
        - python
        - numpy
        - networkx
        - pydotplus
        - parmed
        - vmd-python >=2.0.2
    run:
        - numpy
        - networkx
        - pydotplus
        - parmed
        - networkx
        - pydotplus
        - vmd-python >=2.0.2

about:
    home: dabble-md.readthedocs.org
    license: GPL2
    summary: Membrane protein system builder and parameterizer

